---
- name: This is msg and variables
  hosts: local
  connection: local

  var:
    person1 : Sandeep
    person2 : Krishna

  tasks:
  - name: print msg
    ansible.builtin.debug:
      msg: "{{ person1 }} :Hi how are you"

  - name: print msg
    ansible.builtin.debug:
      msg: "{{ person2 }}Hi I am fine thanks"