---
- name: This is msg and variables
  hosts: local
  connection: local

  vars:
    person1 : "Sandeep"
    person2 : "Krishna"
    person3 : "Pujitha"

  tasks:
  - name: print msg
    ansible.builtin.debug:
      msg: "{{ person1 }} : Hi how are you - > {{ person2 }} , and {{ person3 }}"

  - name: print msg
    ansible.builtin.debug:
      vars:
      person3: "veera sai"
      msg: "{{ person2 }} : Hi I am fine thanks - > {{ person1 }} and how are you {{ person3 }}"