---
- name: removed httpd
  hosts: localhost
  become: yes

  tasks:
    - name: stop httpd
      service:
        name: httpd
        state: stopped
    
    - name: disabled httpd
      service:
        name: httpd
        enabled: no
    
    - name: removed httpd
      yum:
        name: httpd
        state: removed