---
  - name: create ec2 instance and r53 recored
    connection: local
    hosts: local
    vars:
      subnet_id: subnet-004cbeaac8a82d622
      sg_id: sg-0d8458bc7616da8b3
      ami_id: ami-09c813fb71547fc4f
      instance_type: t3.micro  
      instances:
      - mysql
      - frontend
      - backend


    tasks:
    - name: install python lib  
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: pip3.9
      loop:
      - boto3
      - botocore
    - name: create ec2 instance
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        subnet_id: "{{ subnet_id }}"
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        instance_type: "{{ instance_type }}"
      loop: "{{ instances }}"

